apiVersion: v1
kind: Secret
metadata:
  name: anubiswatch-secrets
  namespace: anubiswatch
  labels:
    app.kubernetes.io/name: anubiswatch
type: Opaque
stringData:
  admin-password: "admin"
  # Add other secrets here:
  # encryption-key: ""
  # cluster-secret: ""
