apiVersion: v2
name: anubiswatch
description: A Helm chart for AnubisWatch - Zero-dependency uptime monitoring
type: application
version: 0.1.2
appVersion: "v0.1.2"
home: https://github.com/AnubisWatch/anubiswatch
sources:
  - https://github.com/AnubisWatch/anubiswatch
maintainers:
  - name: AnubisWatch Team
    email: team@anubiswatch.local
keywords:
  - monitoring
  - uptime
  - healthcheck
  - alerting
annotations:
  category: Monitoring
