apiVersion: v1
kind: Secret
metadata:
  name: {{ include "anubiswatch.fullname" . }}-secrets
  labels:
    {{- include "anubiswatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.adminPassword | quote }}
  {{- if .Values.secrets.encryptionKey }}
  encryption-key: {{ .Values.secrets.encryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.clusterSecret }}
  cluster-secret: {{ .Values.secrets.clusterSecret | quote }}
  {{- end }}
