// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/v1/anubis.proto

package anubiswatchv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnubisWatchService_ListSouls_FullMethodName        = "/anubiswatch.v1.AnubisWatchService/ListSouls"
	AnubisWatchService_GetSoul_FullMethodName          = "/anubiswatch.v1.AnubisWatchService/GetSoul"
	AnubisWatchService_CreateSoul_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/CreateSoul"
	AnubisWatchService_UpdateSoul_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/UpdateSoul"
	AnubisWatchService_DeleteSoul_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/DeleteSoul"
	AnubisWatchService_ListJudgments_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/ListJudgments"
	AnubisWatchService_GetSoulJudgments_FullMethodName = "/anubiswatch.v1.AnubisWatchService/GetSoulJudgments"
	AnubisWatchService_JudgeSoul_FullMethodName        = "/anubiswatch.v1.AnubisWatchService/JudgeSoul"
	AnubisWatchService_ListVerdicts_FullMethodName     = "/anubiswatch.v1.AnubisWatchService/ListVerdicts"
	AnubisWatchService_ListChannels_FullMethodName     = "/anubiswatch.v1.AnubisWatchService/ListChannels"
	AnubisWatchService_GetChannel_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/GetChannel"
	AnubisWatchService_CreateChannel_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/CreateChannel"
	AnubisWatchService_UpdateChannel_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/UpdateChannel"
	AnubisWatchService_DeleteChannel_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/DeleteChannel"
	AnubisWatchService_ListRules_FullMethodName        = "/anubiswatch.v1.AnubisWatchService/ListRules"
	AnubisWatchService_GetRule_FullMethodName          = "/anubiswatch.v1.AnubisWatchService/GetRule"
	AnubisWatchService_CreateRule_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/CreateRule"
	AnubisWatchService_UpdateRule_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/UpdateRule"
	AnubisWatchService_DeleteRule_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/DeleteRule"
	AnubisWatchService_ListJourneys_FullMethodName     = "/anubiswatch.v1.AnubisWatchService/ListJourneys"
	AnubisWatchService_GetJourney_FullMethodName       = "/anubiswatch.v1.AnubisWatchService/GetJourney"
	AnubisWatchService_CreateJourney_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/CreateJourney"
	AnubisWatchService_UpdateJourney_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/UpdateJourney"
	AnubisWatchService_DeleteJourney_FullMethodName    = "/anubiswatch.v1.AnubisWatchService/DeleteJourney"
	AnubisWatchService_GetClusterStatus_FullMethodName = "/anubiswatch.v1.AnubisWatchService/GetClusterStatus"
	AnubisWatchService_StreamJudgments_FullMethodName  = "/anubiswatch.v1.AnubisWatchService/StreamJudgments"
	AnubisWatchService_StreamVerdicts_FullMethodName   = "/anubiswatch.v1.AnubisWatchService/StreamVerdicts"
)

// AnubisWatchServiceClient is the client API for AnubisWatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnubisWatchService provides gRPC access to all monitoring resources
type AnubisWatchServiceClient interface {
	// Soul management
	ListSouls(ctx context.Context, in *ListSoulsRequest, opts ...grpc.CallOption) (*ListSoulsResponse, error)
	GetSoul(ctx context.Context, in *GetSoulRequest, opts ...grpc.CallOption) (*Soul, error)
	CreateSoul(ctx context.Context, in *CreateSoulRequest, opts ...grpc.CallOption) (*Soul, error)
	UpdateSoul(ctx context.Context, in *UpdateSoulRequest, opts ...grpc.CallOption) (*Soul, error)
	DeleteSoul(ctx context.Context, in *DeleteSoulRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Judgment (check results)
	ListJudgments(ctx context.Context, in *ListJudgmentsRequest, opts ...grpc.CallOption) (*ListJudgmentsResponse, error)
	GetSoulJudgments(ctx context.Context, in *GetSoulJudgmentsRequest, opts ...grpc.CallOption) (*ListJudgmentsResponse, error)
	JudgeSoul(ctx context.Context, in *JudgeSoulRequest, opts ...grpc.CallOption) (*Judgment, error)
	// Verdict (alert decisions)
	ListVerdicts(ctx context.Context, in *ListVerdictsRequest, opts ...grpc.CallOption) (*ListVerdictsResponse, error)
	// Alert channels
	ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error)
	GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*Channel, error)
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*Channel, error)
	UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*Channel, error)
	DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Alert rules
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*Rule, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*Rule, error)
	UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*Rule, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Journeys
	ListJourneys(ctx context.Context, in *ListJourneysRequest, opts ...grpc.CallOption) (*ListJourneysResponse, error)
	GetJourney(ctx context.Context, in *GetJourneyRequest, opts ...grpc.CallOption) (*Journey, error)
	CreateJourney(ctx context.Context, in *CreateJourneyRequest, opts ...grpc.CallOption) (*Journey, error)
	UpdateJourney(ctx context.Context, in *UpdateJourneyRequest, opts ...grpc.CallOption) (*Journey, error)
	DeleteJourney(ctx context.Context, in *DeleteJourneyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Cluster
	GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterStatus, error)
	// Streaming
	StreamJudgments(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Judgment], error)
	StreamVerdicts(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Verdict], error)
}

type anubisWatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnubisWatchServiceClient(cc grpc.ClientConnInterface) AnubisWatchServiceClient {
	return &anubisWatchServiceClient{cc}
}

func (c *anubisWatchServiceClient) ListSouls(ctx context.Context, in *ListSoulsRequest, opts ...grpc.CallOption) (*ListSoulsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSoulsResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListSouls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetSoul(ctx context.Context, in *GetSoulRequest, opts ...grpc.CallOption) (*Soul, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Soul)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetSoul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) CreateSoul(ctx context.Context, in *CreateSoulRequest, opts ...grpc.CallOption) (*Soul, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Soul)
	err := c.cc.Invoke(ctx, AnubisWatchService_CreateSoul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) UpdateSoul(ctx context.Context, in *UpdateSoulRequest, opts ...grpc.CallOption) (*Soul, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Soul)
	err := c.cc.Invoke(ctx, AnubisWatchService_UpdateSoul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) DeleteSoul(ctx context.Context, in *DeleteSoulRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AnubisWatchService_DeleteSoul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) ListJudgments(ctx context.Context, in *ListJudgmentsRequest, opts ...grpc.CallOption) (*ListJudgmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJudgmentsResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListJudgments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetSoulJudgments(ctx context.Context, in *GetSoulJudgmentsRequest, opts ...grpc.CallOption) (*ListJudgmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJudgmentsResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetSoulJudgments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) JudgeSoul(ctx context.Context, in *JudgeSoulRequest, opts ...grpc.CallOption) (*Judgment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Judgment)
	err := c.cc.Invoke(ctx, AnubisWatchService_JudgeSoul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) ListVerdicts(ctx context.Context, in *ListVerdictsRequest, opts ...grpc.CallOption) (*ListVerdictsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVerdictsResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListVerdicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) ListChannels(ctx context.Context, in *ListChannelsRequest, opts ...grpc.CallOption) (*ListChannelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetChannel(ctx context.Context, in *GetChannelRequest, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, AnubisWatchService_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) UpdateChannel(ctx context.Context, in *UpdateChannelRequest, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, AnubisWatchService_UpdateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) DeleteChannel(ctx context.Context, in *DeleteChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AnubisWatchService_DeleteChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetRule(ctx context.Context, in *GetRuleRequest, opts ...grpc.CallOption) (*Rule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rule)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*Rule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rule)
	err := c.cc.Invoke(ctx, AnubisWatchService_CreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*Rule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rule)
	err := c.cc.Invoke(ctx, AnubisWatchService_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AnubisWatchService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) ListJourneys(ctx context.Context, in *ListJourneysRequest, opts ...grpc.CallOption) (*ListJourneysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJourneysResponse)
	err := c.cc.Invoke(ctx, AnubisWatchService_ListJourneys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetJourney(ctx context.Context, in *GetJourneyRequest, opts ...grpc.CallOption) (*Journey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Journey)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) CreateJourney(ctx context.Context, in *CreateJourneyRequest, opts ...grpc.CallOption) (*Journey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Journey)
	err := c.cc.Invoke(ctx, AnubisWatchService_CreateJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) UpdateJourney(ctx context.Context, in *UpdateJourneyRequest, opts ...grpc.CallOption) (*Journey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Journey)
	err := c.cc.Invoke(ctx, AnubisWatchService_UpdateJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) DeleteJourney(ctx context.Context, in *DeleteJourneyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AnubisWatchService_DeleteJourney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) GetClusterStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatus)
	err := c.cc.Invoke(ctx, AnubisWatchService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *anubisWatchServiceClient) StreamJudgments(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Judgment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnubisWatchService_ServiceDesc.Streams[0], AnubisWatchService_StreamJudgments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Judgment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnubisWatchService_StreamJudgmentsClient = grpc.ServerStreamingClient[Judgment]

func (c *anubisWatchServiceClient) StreamVerdicts(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Verdict], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AnubisWatchService_ServiceDesc.Streams[1], AnubisWatchService_StreamVerdicts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, Verdict]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnubisWatchService_StreamVerdictsClient = grpc.ServerStreamingClient[Verdict]

// AnubisWatchServiceServer is the server API for AnubisWatchService service.
// All implementations must embed UnimplementedAnubisWatchServiceServer
// for forward compatibility.
//
// AnubisWatchService provides gRPC access to all monitoring resources
type AnubisWatchServiceServer interface {
	// Soul management
	ListSouls(context.Context, *ListSoulsRequest) (*ListSoulsResponse, error)
	GetSoul(context.Context, *GetSoulRequest) (*Soul, error)
	CreateSoul(context.Context, *CreateSoulRequest) (*Soul, error)
	UpdateSoul(context.Context, *UpdateSoulRequest) (*Soul, error)
	DeleteSoul(context.Context, *DeleteSoulRequest) (*emptypb.Empty, error)
	// Judgment (check results)
	ListJudgments(context.Context, *ListJudgmentsRequest) (*ListJudgmentsResponse, error)
	GetSoulJudgments(context.Context, *GetSoulJudgmentsRequest) (*ListJudgmentsResponse, error)
	JudgeSoul(context.Context, *JudgeSoulRequest) (*Judgment, error)
	// Verdict (alert decisions)
	ListVerdicts(context.Context, *ListVerdictsRequest) (*ListVerdictsResponse, error)
	// Alert channels
	ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error)
	GetChannel(context.Context, *GetChannelRequest) (*Channel, error)
	CreateChannel(context.Context, *CreateChannelRequest) (*Channel, error)
	UpdateChannel(context.Context, *UpdateChannelRequest) (*Channel, error)
	DeleteChannel(context.Context, *DeleteChannelRequest) (*emptypb.Empty, error)
	// Alert rules
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	GetRule(context.Context, *GetRuleRequest) (*Rule, error)
	CreateRule(context.Context, *CreateRuleRequest) (*Rule, error)
	UpdateRule(context.Context, *UpdateRuleRequest) (*Rule, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*emptypb.Empty, error)
	// Journeys
	ListJourneys(context.Context, *ListJourneysRequest) (*ListJourneysResponse, error)
	GetJourney(context.Context, *GetJourneyRequest) (*Journey, error)
	CreateJourney(context.Context, *CreateJourneyRequest) (*Journey, error)
	UpdateJourney(context.Context, *UpdateJourneyRequest) (*Journey, error)
	DeleteJourney(context.Context, *DeleteJourneyRequest) (*emptypb.Empty, error)
	// Cluster
	GetClusterStatus(context.Context, *emptypb.Empty) (*ClusterStatus, error)
	// Streaming
	StreamJudgments(*StreamRequest, grpc.ServerStreamingServer[Judgment]) error
	StreamVerdicts(*StreamRequest, grpc.ServerStreamingServer[Verdict]) error
	mustEmbedUnimplementedAnubisWatchServiceServer()
}

// UnimplementedAnubisWatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnubisWatchServiceServer struct{}

func (UnimplementedAnubisWatchServiceServer) ListSouls(context.Context, *ListSoulsRequest) (*ListSoulsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSouls not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetSoul(context.Context, *GetSoulRequest) (*Soul, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoul not implemented")
}
func (UnimplementedAnubisWatchServiceServer) CreateSoul(context.Context, *CreateSoulRequest) (*Soul, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSoul not implemented")
}
func (UnimplementedAnubisWatchServiceServer) UpdateSoul(context.Context, *UpdateSoulRequest) (*Soul, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSoul not implemented")
}
func (UnimplementedAnubisWatchServiceServer) DeleteSoul(context.Context, *DeleteSoulRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSoul not implemented")
}
func (UnimplementedAnubisWatchServiceServer) ListJudgments(context.Context, *ListJudgmentsRequest) (*ListJudgmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJudgments not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetSoulJudgments(context.Context, *GetSoulJudgmentsRequest) (*ListJudgmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSoulJudgments not implemented")
}
func (UnimplementedAnubisWatchServiceServer) JudgeSoul(context.Context, *JudgeSoulRequest) (*Judgment, error) {
	return nil, status.Error(codes.Unimplemented, "method JudgeSoul not implemented")
}
func (UnimplementedAnubisWatchServiceServer) ListVerdicts(context.Context, *ListVerdictsRequest) (*ListVerdictsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVerdicts not implemented")
}
func (UnimplementedAnubisWatchServiceServer) ListChannels(context.Context, *ListChannelsRequest) (*ListChannelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetChannel(context.Context, *GetChannelRequest) (*Channel, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedAnubisWatchServiceServer) CreateChannel(context.Context, *CreateChannelRequest) (*Channel, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedAnubisWatchServiceServer) UpdateChannel(context.Context, *UpdateChannelRequest) (*Channel, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (UnimplementedAnubisWatchServiceServer) DeleteChannel(context.Context, *DeleteChannelRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChannel not implemented")
}
func (UnimplementedAnubisWatchServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetRule(context.Context, *GetRuleRequest) (*Rule, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRule not implemented")
}
func (UnimplementedAnubisWatchServiceServer) CreateRule(context.Context, *CreateRuleRequest) (*Rule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRule not implemented")
}
func (UnimplementedAnubisWatchServiceServer) UpdateRule(context.Context, *UpdateRuleRequest) (*Rule, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedAnubisWatchServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedAnubisWatchServiceServer) ListJourneys(context.Context, *ListJourneysRequest) (*ListJourneysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJourneys not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetJourney(context.Context, *GetJourneyRequest) (*Journey, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJourney not implemented")
}
func (UnimplementedAnubisWatchServiceServer) CreateJourney(context.Context, *CreateJourneyRequest) (*Journey, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateJourney not implemented")
}
func (UnimplementedAnubisWatchServiceServer) UpdateJourney(context.Context, *UpdateJourneyRequest) (*Journey, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateJourney not implemented")
}
func (UnimplementedAnubisWatchServiceServer) DeleteJourney(context.Context, *DeleteJourneyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJourney not implemented")
}
func (UnimplementedAnubisWatchServiceServer) GetClusterStatus(context.Context, *emptypb.Empty) (*ClusterStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedAnubisWatchServiceServer) StreamJudgments(*StreamRequest, grpc.ServerStreamingServer[Judgment]) error {
	return status.Error(codes.Unimplemented, "method StreamJudgments not implemented")
}
func (UnimplementedAnubisWatchServiceServer) StreamVerdicts(*StreamRequest, grpc.ServerStreamingServer[Verdict]) error {
	return status.Error(codes.Unimplemented, "method StreamVerdicts not implemented")
}
func (UnimplementedAnubisWatchServiceServer) mustEmbedUnimplementedAnubisWatchServiceServer() {}
func (UnimplementedAnubisWatchServiceServer) testEmbeddedByValue()                            {}

// UnsafeAnubisWatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnubisWatchServiceServer will
// result in compilation errors.
type UnsafeAnubisWatchServiceServer interface {
	mustEmbedUnimplementedAnubisWatchServiceServer()
}

func RegisterAnubisWatchServiceServer(s grpc.ServiceRegistrar, srv AnubisWatchServiceServer) {
	// If the following call panics, it indicates UnimplementedAnubisWatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnubisWatchService_ServiceDesc, srv)
}

func _AnubisWatchService_ListSouls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSoulsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListSouls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListSouls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListSouls(ctx, req.(*ListSoulsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetSoul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetSoul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetSoul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetSoul(ctx, req.(*GetSoulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_CreateSoul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSoulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).CreateSoul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_CreateSoul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).CreateSoul(ctx, req.(*CreateSoulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_UpdateSoul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSoulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).UpdateSoul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_UpdateSoul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).UpdateSoul(ctx, req.(*UpdateSoulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_DeleteSoul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSoulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).DeleteSoul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_DeleteSoul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).DeleteSoul(ctx, req.(*DeleteSoulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_ListJudgments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJudgmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListJudgments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListJudgments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListJudgments(ctx, req.(*ListJudgmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetSoulJudgments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSoulJudgmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetSoulJudgments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetSoulJudgments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetSoulJudgments(ctx, req.(*GetSoulJudgmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_JudgeSoul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JudgeSoulRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).JudgeSoul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_JudgeSoul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).JudgeSoul(ctx, req.(*JudgeSoulRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_ListVerdicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVerdictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListVerdicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListVerdicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListVerdicts(ctx, req.(*ListVerdictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListChannels(ctx, req.(*ListChannelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetChannel(ctx, req.(*GetChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_UpdateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).UpdateChannel(ctx, req.(*UpdateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_DeleteChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).DeleteChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_DeleteChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).DeleteChannel(ctx, req.(*DeleteChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetRule(ctx, req.(*GetRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_CreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).UpdateRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_ListJourneys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJourneysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).ListJourneys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_ListJourneys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).ListJourneys(ctx, req.(*ListJourneysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetJourney(ctx, req.(*GetJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_CreateJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).CreateJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_CreateJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).CreateJourney(ctx, req.(*CreateJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_UpdateJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).UpdateJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_UpdateJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).UpdateJourney(ctx, req.(*UpdateJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_DeleteJourney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJourneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).DeleteJourney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_DeleteJourney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).DeleteJourney(ctx, req.(*DeleteJourneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnubisWatchServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnubisWatchService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnubisWatchServiceServer).GetClusterStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnubisWatchService_StreamJudgments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnubisWatchServiceServer).StreamJudgments(m, &grpc.GenericServerStream[StreamRequest, Judgment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnubisWatchService_StreamJudgmentsServer = grpc.ServerStreamingServer[Judgment]

func _AnubisWatchService_StreamVerdicts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnubisWatchServiceServer).StreamVerdicts(m, &grpc.GenericServerStream[StreamRequest, Verdict]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AnubisWatchService_StreamVerdictsServer = grpc.ServerStreamingServer[Verdict]

// AnubisWatchService_ServiceDesc is the grpc.ServiceDesc for AnubisWatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnubisWatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anubiswatch.v1.AnubisWatchService",
	HandlerType: (*AnubisWatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSouls",
			Handler:    _AnubisWatchService_ListSouls_Handler,
		},
		{
			MethodName: "GetSoul",
			Handler:    _AnubisWatchService_GetSoul_Handler,
		},
		{
			MethodName: "CreateSoul",
			Handler:    _AnubisWatchService_CreateSoul_Handler,
		},
		{
			MethodName: "UpdateSoul",
			Handler:    _AnubisWatchService_UpdateSoul_Handler,
		},
		{
			MethodName: "DeleteSoul",
			Handler:    _AnubisWatchService_DeleteSoul_Handler,
		},
		{
			MethodName: "ListJudgments",
			Handler:    _AnubisWatchService_ListJudgments_Handler,
		},
		{
			MethodName: "GetSoulJudgments",
			Handler:    _AnubisWatchService_GetSoulJudgments_Handler,
		},
		{
			MethodName: "JudgeSoul",
			Handler:    _AnubisWatchService_JudgeSoul_Handler,
		},
		{
			MethodName: "ListVerdicts",
			Handler:    _AnubisWatchService_ListVerdicts_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _AnubisWatchService_ListChannels_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _AnubisWatchService_GetChannel_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _AnubisWatchService_CreateChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _AnubisWatchService_UpdateChannel_Handler,
		},
		{
			MethodName: "DeleteChannel",
			Handler:    _AnubisWatchService_DeleteChannel_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _AnubisWatchService_ListRules_Handler,
		},
		{
			MethodName: "GetRule",
			Handler:    _AnubisWatchService_GetRule_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _AnubisWatchService_CreateRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _AnubisWatchService_UpdateRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _AnubisWatchService_DeleteRule_Handler,
		},
		{
			MethodName: "ListJourneys",
			Handler:    _AnubisWatchService_ListJourneys_Handler,
		},
		{
			MethodName: "GetJourney",
			Handler:    _AnubisWatchService_GetJourney_Handler,
		},
		{
			MethodName: "CreateJourney",
			Handler:    _AnubisWatchService_CreateJourney_Handler,
		},
		{
			MethodName: "UpdateJourney",
			Handler:    _AnubisWatchService_UpdateJourney_Handler,
		},
		{
			MethodName: "DeleteJourney",
			Handler:    _AnubisWatchService_DeleteJourney_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _AnubisWatchService_GetClusterStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJudgments",
			Handler:       _AnubisWatchService_StreamJudgments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamVerdicts",
			Handler:       _AnubisWatchService_StreamVerdicts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/v1/anubis.proto",
}
